import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import {ClerkProvider} from '@clerk/nextjs'
import { Toaster } from "react-hot-toast"


const raleway = localFont({
  src:'../fonts/font.woff2',
  variable:'--font-raleway',
  weight:'100 900'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={`${raleway.variable}anitialiased`}>
        <Header/>
        {children}
        <Footer/>
        <Toaster position="bottom-right" toastOptions={{
          style:{
            background:'#ffffff'
          }
        }}/>
      </body>
    </html>
    </ClerkProvider>
  );
}
